# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Checkout common
      uses: actions/checkout@v2.2.0
      with:
        repository: "AuroraPowered/AuroraCraft-Common"
        path: common

    - name: Grant execute permission for gradlew (common)
      run: chmod +x gradlew
      working-directory: ./common
      
    - name: Install common with Gradle
      run: gradlew install
      working-directory: ./common

    - name: Grant execute permission for gradlew (this project)
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew build

    - name: Upload built jars to Build Artifact
      uses: actions/upload-artifact@v2
      with:
        name: auroracraft-output
        path: build/libs
